---

model: 'SparseTSF'
data: 'ETTm2'
root_path: './data/'
data_path: 'ETT 2.csv'
features: 'M'
target: 'OT'
freq: 't'
detail_freq: 'h'
checkpoints: './checkpoints/'
seq_len: 720
label_len: 48
pred_len: 192
period_len: 24

enc_in: 7
dec_in: 1d
c_out: 1
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
s_layers: '3,2,1'
d_ff: 2048
factor: 5
padding: 0
distil: True
dropout: 0.05
attn: 'prob'
embed: 'timeF'
activation: 'gelu'
output_attention: False
do_predict: False
mix: True
cols: '+'
num_workers: 0
itr: 1
train_epochs: 30
batch_size: 256
patience: 5
learning_rate: 0.02
des: 'SparseTSF_ms'
loss: 'mse'
lradj: 'type3'

use_amp: False
inverse: False
seed: 2030

device: "GPU"
do_train: True
ckpt_path: "./SparseTSF_test.ckpt"